language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - pip install -e .
  - pip install -e .[lint]
  - pip install -e .[test]
# command to run tests
script:
  - pytest tests/
